name: shintaikan
description: Die Karate Club Shintaikan e.V. app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 3.0.0+32

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  #Firebase
  firebase_core: ^1.4.0
  firebase_messaging:
  cloud_firestore: ^2.4.0
  cloud_functions: ^3.0.0

  connectivity: ^3.0.6

  cupertino_icons:
  outline_material_icons:

  webview_flutter:
  flutter_statusbarcolor:
  package_info:
  flutter_html:
  intl:
  url_launcher:
  flutter_wordpress: ^0.2.0
dependency_overrides:
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/